language: c

arch:
  - amd64

os:
  - linux

dist:
  - bionic

sudo: required

ompiler:
  - gcc

before_install:
    - sudo apt-get install -y build-essential gcc-7-multilib
    - sudo apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
    - sudo apt-get install -y qemu-user
    - sudo apt-get install -y python3

script:
    - make check
